sudo: required
dist: trusty
language: node_js
node_js:
  - '10'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm i -g @angular/cli
- npm i -g karma
- npm i -g typescript@2.9.1
- npm i
- ng build

script: ng test --karma-config karma.conf.js --watch=false
