sudo: required
dist: trusty
language: node_js
node_js:
  - '10'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g @angular/cli
- npm install -g karma
- npm install
- ng build

notification:
  slack: 
    secure: KcdgU3iLp3SclS+naFiL0TZ9ZIDKQcq3aW9Q8D52DE8Wpv9FCZ/Ul0QBwCPLdVVJnP9/xcRfcE+HB+DLf0+YWy0XOcUtMuHnpBrdYDiVcx6dBRG0CQbSz/voSa+ax0qy95exnQBnTlYoJyq25n6SiwgmQFv5TD5xYiKfyKIVICh/LcpGocBRPow0skPy4WK0Mv0dcSpBvvzwweW5165++G6Qa1NdAymUqptK2z77lIXRzX3qT1Z2Z+Rc1jo4t9TZw8GfMg6i6qXDGuDJN56hqlLW7jJsPphpIOxeX+lvz36RxtzwvDiLkNjqNEONULsUpDJO1bI43jFejubv+lkPXpjbRQEyIuAf48uaBo9JajZ0uEwXQsD3BpcHLRTgj5PyLA9/rVXJXwqjhappbds74WTZQ5F9RgHZs1Ob/s0grw56uoaYQYcBzAPLjqnul1OXu2CMHySVOW4DWHbqM2wosSxD0hktHvQ+y9tV+MQV+nCqYyRz9MZOXp+TGANv2buCTXrehPIFaLSP8HWuZtqULz7EG1Keg87SFwo6dyusfL1dX6mO/c8bt0jEqN0DLXyfyhmBfQ57cX0lvTH6MRMgbw0i/wqvTGAXp5WrKmLZedLIUBL6ZFbiUiILJsqnSQjqY04vCBM1RwdRn8BmT8y0/ofhsHxgh2eucDRmE6ssgik=
    on_success: always
    on_failure: always

script: ng test --karma-config karma.conf.js --watch=false
